import { initializeApp, getApps, getApp } from 'firebase/app';
import {
  getFirestore,
  doc,
  getDoc,
  setDoc,
  updateDoc,
  deleteDoc,
  collection,
  query,
  where,
  getDocs,
  onSnapshot,
} from 'firebase/firestore';
import firebaseConfig from '../../firebase-applet-config.json';
import {
  Household,
  HouseholdSettings,
  SubcategoryConfig,
  Transaction,
  UserAccount,
  WeekGamble,
  WeekScoreRecord,
  ChatMessage,
} from '../types';

// Initialize Firebase App
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
export const db = firebaseConfig.firestoreDatabaseId
  ? getFirestore(app, firebaseConfig.firestoreDatabaseId)
  : getFirestore(app);

// Seed default sample data if household does not exist
export const DEFAULT_SUBCATEGORIES: SubcategoryConfig[] = [
  {
    id: 'rent',
    name: 'Rent / Mortgage',
    mainCategory: 'required',
    spendingType: 'fixed',
    targetMonthlyBudget: 1800,
    iconName: 'Home',
    description: 'Fixed housing cost prorated across weeks',
  },
  {
    id: 'groceries',
    name: 'Groceries & Essentials',
    mainCategory: 'required',
    spendingType: 'variable',
    targetMonthlyBudget: 600,
    iconName: 'ShoppingCart',
    description: 'Weekly grocery store runs and household supplies',
  },
  {
    id: 'utilities',
    name: 'Utilities (Electric, Water, Gas)',
    mainCategory: 'required',
    spendingType: 'hybrid',
    targetMonthlyBudget: 220,
    fixedBaseAmount: 140,
    iconName: 'Zap',
    description: 'Base utility delivery fees + variable usage',
  },
  {
    id: 'bills',
    name: 'Bills (Internet, Cell, Insurance)',
    mainCategory: 'required',
    spendingType: 'hybrid',
    targetMonthlyBudget: 280,
    fixedBaseAmount: 220,
    iconName: 'Phone',
    description: 'Fixed phone plans & fiber internet + variable extras',
  },
  {
    id: 'transit',
    name: 'Transit & Commuting',
    mainCategory: 'required',
    spendingType: 'variable',
    targetMonthlyBudget: 200,
    iconName: 'Car',
    description: 'Gas, bridge tolls, transit passes',
  },
  {
    id: 'dining',
    name: 'Restaurants & Coffee',
    mainCategory: 'discretionary',
    spendingType: 'variable',
    targetMonthlyBudget: 450,
    iconName: 'Utensils',
    description: 'Date nights, takeout, and weekday coffees',
  },
  {
    id: 'entertainment',
    name: 'Activities & Hobbies',
    mainCategory: 'discretionary',
    spendingType: 'variable',
    targetMonthlyBudget: 300,
    iconName: 'Film',
    description: 'Concerts, museum passes, weekend trips',
  },
  {
    id: 'shopping',
    name: 'Shopping & Apparel',
    mainCategory: 'discretionary',
    spendingType: 'variable',
    targetMonthlyBudget: 250,
    iconName: 'ShoppingBag',
    description: 'Clothes, books, gadgets, home decor',
  },
  {
    id: 'wellness',
    name: 'Personal Care & Fitness',
    mainCategory: 'discretionary',
    spendingType: 'variable',
    targetMonthlyBudget: 180,
    iconName: 'Sparkles',
    description: 'Haircuts, gym passes, cosmetics',
  },
  {
    id: 'vacation_fund',
    name: 'Vacation & Travel Fund',
    mainCategory: 'reserved',
    spendingType: 'fixed',
    targetMonthlyBudget: 400,
    iconName: 'Plane',
    description: 'Monthly savings locked for our next trip',
  },
  {
    id: 'emergency_fund',
    name: 'Emergency Buffer',
    mainCategory: 'reserved',
    spendingType: 'fixed',
    targetMonthlyBudget: 300,
    iconName: 'Shield',
    description: 'Buffer for unexpected repairs or medical care',
  },
  {
    id: 'special_goals',
    name: 'Future Joint Goals',
    mainCategory: 'reserved',
    spendingType: 'variable',
    targetMonthlyBudget: 250,
    iconName: 'PiggyBank',
    description: 'Saving for furniture upgrade & investments',
  },
];

export const createEmptyHousehold = (
  id: string,
  name: string,
  inviteCode: string,
  partner1?: { name: string; avatarEmoji?: string; color: string },
  partner2?: { name: string; avatarEmoji?: string; color: string }
): Household => {
  return {
    id,
    name: name || 'Our Household',
    inviteCode: inviteCode || id.slice(0, 6).toUpperCase(),
    createdAt: Date.now(),
    settings: {
      calendarMode: 'calendar',
      firstDayOfWeek: 0,
      currencySymbol: '$',
      income: {
        totalMonthlyIncome: 0,
        partner1Income: 0,
        partner2Income: 0,
        splitMode: 'individual',
      },
      parentBudgets: {
        required: 0,
        discretionary: 0,
        reserved: 0,
      },
      partner1: {
        id: 'partner1',
        name: partner1?.name || 'Partner 1',
        avatarEmoji: partner1?.avatarEmoji || 'botanical_leaf',
        color: partner1?.color || '#5B8296',
      },
      partner2: {
        id: 'partner2',
        name: partner2?.name || 'Partner 2',
        avatarEmoji: partner2?.avatarEmoji || 'hearth_flame',
        color: partner2?.color || '#A26A42',
      },
    },
    subcategories: [],
    score: {
      totalPoints: 0,
      currentStreakWeeks: 0,
      bestStreakWeeks: 0,
      history: [],
    },
    gambles: [],
    sponges: [],
    unlockedBadgeIds: [],
  };
};

export const createDefaultHousehold = (
  id: string,
  name: string,
  inviteCode: string,
  partner1?: { name: string; avatarEmoji?: string; color: string },
  partner2?: { name: string; avatarEmoji?: string; color: string }
): Household => {
  return {
    id,
    name: name || 'Alex & Jordan’s Haven',
    inviteCode: inviteCode || id.slice(0, 6).toUpperCase(),
    createdAt: Date.now(),
    settings: {
      calendarMode: 'calendar',
      firstDayOfWeek: 0,
      currencySymbol: '$',
      income: {
        totalMonthlyIncome: 6500,
        partner1Income: 3500,
        partner2Income: 3000,
        splitMode: 'individual',
      },
      parentBudgets: {
        required: 2900,
        discretionary: 1180,
        reserved: 950,
      },
      partner1: {
        id: 'partner1',
        name: partner1?.name || 'Alex',
        avatarEmoji: partner1?.avatarEmoji || 'botanical_leaf',
        color: partner1?.color || '#5B8296',
      },
      partner2: {
        id: 'partner2',
        name: partner2?.name || 'Jordan',
        avatarEmoji: partner2?.avatarEmoji || 'hearth_flame',
        color: partner2?.color || '#A26A42',
      },
    },
    subcategories: DEFAULT_SUBCATEGORIES,
    score: {
      totalPoints: 1250,
      currentStreakWeeks: 2,
      bestStreakWeeks: 4,
      history: [
        {
          weekNumber: 1,
          monthKey: '2026-08',
          weekLabel: 'Week 1 (Aug 1 - Aug 7)',
          totalBudget: 1125,
          totalSpent: 980,
          netDiff: 145,
          basePoints: 500,
          streakWeekCount: 1,
          streakBonusPercent: 0,
          streakBonusPoints: 0,
          gambleImpact: 0,
          totalWeekScore: 500,
          evaluatedAt: Date.now() - 14 * 24 * 60 * 60 * 1000,
        },
        {
          weekNumber: 2,
          monthKey: '2026-08',
          weekLabel: 'Week 2 (Aug 8 - Aug 14)',
          totalBudget: 1125,
          totalSpent: 1040,
          netDiff: 85,
          basePoints: 500,
          streakWeekCount: 2,
          streakBonusPercent: 20,
          streakBonusPoints: 100,
          gambleImpact: 150,
          totalWeekScore: 750,
          evaluatedAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
        },
      ],
    },
    gambles: [
      {
        id: 'g-demo-1',
        householdId: id,
        partnerId: 'partner1',
        weekNumber: 2,
        monthKey: '2026-08',
        overspentAmount: 60,
        gambleAmount: 100,
        status: 'won',
        createdAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
        resolvedAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
        scoreImpact: 150,
        notes: 'Packed lunches all week & underspent dining by $80!',
      },
    ],
    sponges: [
      {
        id: 'sponge-starter-1',
        title: 'Weekend Dining Overage Task Set',
        reason: 'Discretionary weekend dining exceeded weekly allowance by $45',
        weekNumber: 1,
        monthKey: '2026-08',
        overspentAmount: 45,
        penaltyPoints: 50,
        status: 'active',
        createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
        tasks: [
          {
            id: 't-sponge-1',
            title: 'Cook 2 Cozy Dinners at Home',
            description: 'Prepare delicious homemade meals together instead of dining out',
            pointsRestored: 30,
            completed: true,
            completedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
            completedByPartnerId: 'partner1',
          },
          {
            id: 't-sponge-2',
            title: 'Home Barista Mornings (3 Days)',
            description: 'Brew coffee at home for 3 consecutive mornings',
            pointsRestored: 20,
            completed: false,
          },
          {
            id: 't-sponge-3',
            title: '24-Hour Non-Essential No-Spend Day',
            description: 'Commit to zero non-essential spending for 24 hours',
            pointsRestored: 35,
            completed: false,
          },
        ],
      },
    ],
    unlockedBadgeIds: ['first_log', 'under_budget_week', 'streak_2'],
  };
};

export const createDefaultSampleTransactions = (householdId: string): Transaction[] => {
  const now = Date.now();
  return [
    {
      id: `tx-init-1-${householdId}`,
      householdId,
      partnerId: 'partner1',
      partnerName: 'Alex',
      mainCategory: 'required',
      subcategoryId: 'groceries',
      subcategoryName: 'Groceries & Essentials',
      amount: 112.5,
      date: '2026-08-16',
      note: 'Weekly grocery run at Trader Joe’s (produce, dairy, pantry)',
      spendingType: 'variable',
      reactions: { partner2: ['heart', 'leaf'] },
      createdAt: now - 4 * 24 * 60 * 60 * 1000,
    },
    {
      id: `tx-init-2-${householdId}`,
      householdId,
      partnerId: 'partner2',
      partnerName: 'Jordan',
      mainCategory: 'discretionary',
      subcategoryId: 'dining',
      subcategoryName: 'Restaurants & Coffee',
      amount: 48.0,
      date: '2026-08-18',
      note: 'Ramen date night in Japantown',
      spendingType: 'variable',
      reactions: { partner1: ['heart', 'star'] },
      createdAt: now - 2 * 24 * 60 * 60 * 1000,
    },
    {
      id: `tx-init-3-${householdId}`,
      householdId,
      partnerId: 'partner1',
      partnerName: 'Alex',
      mainCategory: 'discretionary',
      subcategoryId: 'dining',
      subcategoryName: 'Restaurants & Coffee',
      amount: 14.25,
      date: '2026-08-19',
      note: 'Matcha lattes & pastries at local cafe',
      spendingType: 'variable',
      reactions: { partner2: ['coffee'] },
      createdAt: now - 1 * 24 * 60 * 60 * 1000,
    },
    {
      id: `tx-init-4-${householdId}`,
      householdId,
      partnerId: 'partner2',
      partnerName: 'Jordan',
      mainCategory: 'required',
      subcategoryId: 'utilities',
      subcategoryName: 'Utilities (Electric, Water, Gas)',
      amount: 45.0,
      date: '2026-08-17',
      note: 'Summer air conditioning surcharge (variable overage)',
      spendingType: 'hybrid',
      reactions: { partner1: ['shield'] },
      createdAt: now - 3 * 24 * 60 * 60 * 1000,
    },
    {
      id: `tx-init-5-${householdId}`,
      partnerId: 'partner1',
      partnerName: 'Alex',
      householdId,
      mainCategory: 'required',
      subcategoryId: 'transit',
      subcategoryName: 'Transit & Commuting',
      amount: 38.0,
      date: '2026-08-15',
      note: 'Gas station refill',
      spendingType: 'variable',
      reactions: { partner2: ['thumbs_up'] },
      createdAt: now - 5 * 24 * 60 * 60 * 1000,
    },
    {
      id: `tx-init-6-${householdId}`,
      householdId,
      partnerId: 'partner1',
      partnerName: 'Alex',
      mainCategory: 'required',
      subcategoryId: 'bills',
      subcategoryName: 'Bills (Internet, Cell, Insurance)',
      amount: 35.0,
      date: '2026-08-05',
      note: 'Roaming day pass add-on (variable overage)',
      spendingType: 'hybrid',
      reactions: { partner2: ['thumbs_up'] },
      createdAt: now - 15 * 24 * 60 * 60 * 1000,
    },
    {
      id: `tx-init-7-${householdId}`,
      householdId,
      partnerId: 'partner2',
      partnerName: 'Jordan',
      mainCategory: 'discretionary',
      subcategoryId: 'entertainment',
      subcategoryName: 'Activities & Hobbies',
      amount: 65.0,
      date: '2026-08-08',
      note: 'Weekend outdoor movie night tickets',
      spendingType: 'variable',
      reactions: { partner1: ['sparkles'] },
      createdAt: now - 12 * 24 * 60 * 60 * 1000,
    },
    {
      id: `tx-init-8-${householdId}`,
      householdId,
      partnerId: 'partner1',
      partnerName: 'Alex',
      mainCategory: 'discretionary',
      subcategoryId: 'shopping',
      subcategoryName: 'Shopping & Apparel',
      amount: 42.0,
      date: '2026-08-10',
      note: 'Botanical planter & potting soil for garden',
      spendingType: 'variable',
      reactions: { partner2: ['leaf'] },
      createdAt: now - 10 * 24 * 60 * 60 * 1000,
    },
  ];
};

export const createDefaultSampleMessages = (householdId: string): ChatMessage[] => {
  const now = Date.now();
  return [
    {
      id: `msg-1-${householdId}`,
      householdId,
      partnerId: 'partner1',
      partnerName: 'Alex',
      partnerAvatar: 'botanical_leaf',
      content: 'Hey Jordan! Just did our grocery run for this week’s essentials.',
      attachedTransaction: {
        id: `tx-init-1-${householdId}`,
        householdId,
        partnerId: 'partner1',
        partnerName: 'Alex',
        mainCategory: 'required',
        subcategoryId: 'groceries',
        subcategoryName: 'Groceries & Essentials',
        amount: 112.5,
        date: '2026-08-16',
        note: 'Weekly grocery run (produce, dairy, pantry)',
        spendingType: 'variable',
        reactions: { partner2: ['heart', 'leaf'] },
        createdAt: now - 4 * 24 * 60 * 60 * 1000,
      },
      reactions: { partner2: ['heart', 'leaf'] },
      createdAt: now - 4 * 24 * 60 * 60 * 1000,
    },
    {
      id: `msg-2-${householdId}`,
      householdId,
      partnerId: 'partner2',
      partnerName: 'Jordan',
      partnerAvatar: 'hearth_flame',
      content: 'Awesome! We are well within our weekly budget for groceries.',
      gifUrl: 'https://media.giphy.com/media/l41lI4bYmcsPJX9Go/giphy.gif',
      gifTitle: 'High Five',
      reactions: { partner1: ['thumbs_up'] },
      createdAt: now - 3 * 24 * 60 * 60 * 1000,
    },
    {
      id: `msg-3-${householdId}`,
      householdId,
      partnerId: 'partner2',
      partnerName: 'Jordan',
      partnerAvatar: 'hearth_flame',
      content: 'Sharing the Ramen date night from yesterday. It was delicious!',
      attachedTransaction: {
        id: `tx-init-2-${householdId}`,
        householdId,
        partnerId: 'partner2',
        partnerName: 'Jordan',
        mainCategory: 'discretionary',
        subcategoryId: 'dining',
        subcategoryName: 'Restaurants & Coffee',
        amount: 48.0,
        date: '2026-08-18',
        note: 'Ramen date night in Japantown',
        spendingType: 'variable',
        reactions: { partner1: ['heart', 'star'] },
        createdAt: now - 2 * 24 * 60 * 60 * 1000,
      },
      reactions: { partner1: ['heart'] },
      createdAt: now - 2 * 24 * 60 * 60 * 1000,
    },
  ];
};
